In [1]:
import torch

x = torch.empty(2, 5)
x.size()

torch.Size([2, 5])

In [2]:
x.fill_(1.125)

tensor([[1.1250, 1.1250, 1.1250, 1.1250, 1.1250],
        [1.1250, 1.1250, 1.1250, 1.1250, 1.1250]])

In [3]:
x.mean()

tensor(1.1250)

In [4]:
x.std()

tensor(0.)

In [5]:
x.sum()

tensor(11.2500)

In [6]:
x.sum().item()

11.25

In [7]:
x = torch.tensor([[11., 12., 13.], [21., 22., 23.]])
x[1, 2]

tensor(23.)

In [8]:
x = torch.tensor([10., 20., 30.])
y = torch.tensor([11., 21., 31.])
x + y

tensor([21., 41., 61.])

In [9]:
x * y

tensor([110., 420., 930.])

In [10]:
x**2

tensor([100., 400., 900.])

In [11]:
m = torch.tensor([[0., 0., 3.],
                  [0., 2., 0.,],
                  [1., 0., 0.]])

In [12]:
m.mv(x)

tensor([90., 40., 10.])

In [13]:
m @ x

tensor([90., 40., 10.])

In [14]:
x @ m

tensor([30., 40., 30.])

In [15]:
x = torch.empty(2, 4).random_(10)

In [16]:
x

tensor([[2., 0., 3., 9.],
        [2., 4., 9., 0.]])

In [17]:
x[0]

tensor([2., 0., 3., 9.])

In [18]:
x[0, :]

tensor([2., 0., 3., 9.])

In [19]:
x[:, 0]

tensor([2., 2.])

In [20]:
x[:, 1:3] = -1

In [21]:
x

tensor([[ 2., -1., -1.,  9.],
        [ 2., -1., -1.,  0.]])

In [22]:
y = torch.empty(3).normal_()
y

tensor([-1.5028,  0.1935,  0.2243])

In [23]:
m = torch.empty(3, 3).normal_()

In [24]:
q, _ = torch.lstsq(y, m)

/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:1: UserWarning: torch.lstsq is deprecated in favor of torch.linalg.lstsq and will be removed in a future PyTorch release.
torch.linalg.lstsq has reversed arguments and does not return the QR decomposition in the returned tuple (although it returns other information about the problem).
To get the qr decomposition consider using torch.linalg.qr.
The returned solution in torch.lstsq stored the residuals of the solution in the last m - n columns of the returned value whenever m > n. In torch.linalg.lstsq, the residuals in the field 'residuals' of the returned named tuple.
The unpacking of the solution, as in
X, _ = torch.lstsq(B, A).solution[:A.size(1)]
should be replaced with
X = torch.linalg.lstsq(A, B).solution (Triggered internally at  ../aten/src/ATen/native/BatchLinearAlgebra.cpp:4158.)
  """Entry point for launching an IPython kernel.


In [25]:
torch.mm(m, q)

tensor([[-1.5028],
        [ 0.1935],
        [ 0.2243]])

In [26]:
q

tensor([[-12.5898],
        [ -7.6263],
        [ 20.4737]])

In [27]:
m

tensor([[ 0.9145, -0.0374,  0.4750],
        [ 0.0180,  0.0999,  0.0577],
        [-0.1606,  0.6320,  0.1476]])

In [28]:
m @ q

tensor([[-1.5028],
        [ 0.1935],
        [ 0.2243]])

In [29]:
x = torch.zeros(1, 3)
x.dtype, x.device

(torch.float32, device(type='cpu'))

In [30]:
x = x.long()
x.dtype, x.device

(torch.int64, device(type='cpu'))

In [31]:
x = x.to('cuda')
x.dtype, x.device

(torch.int64, device(type='cuda', index=0))

In [32]:
x = torch.tensor([[1, 3, 0],
                  [2, 4, 6]])

In [33]:
x.t()

tensor([[1, 2],
        [3, 4],
        [0, 6]])

In [34]:
x.view(-1)

tensor([1, 3, 0, 2, 4, 6])

In [35]:
x.view(3, -1)

tensor([[1, 3],
        [0, 2],
        [4, 6]])

In [36]:
x[:, 1:3]

tensor([[3, 0],
        [4, 6]])

In [37]:
x.view(1, 2, 3).expand(3, 2, 3)

tensor([[[1, 3, 0],
         [2, 4, 6]],

        [[1, 3, 0],
         [2, 4, 6]],

        [[1, 3, 0],
         [2, 4, 6]]])

In [38]:
x = torch.tensor([[[1, 2, 1],
                   [2, 1, 2]],
                  [[3, 0, 3],
                   [0, 3, 0]]])

In [39]:
x[0:1, :, :]

tensor([[[1, 2, 1],
         [2, 1, 2]]])

In [40]:
x[:, :, 0:2]

tensor([[[1, 2],
         [2, 1]],

        [[3, 0],
         [0, 3]]])

In [41]:
x.transpose(0, 1)

tensor([[[1, 2, 1],
         [3, 0, 3]],

        [[2, 1, 2],
         [0, 3, 0]]])

In [42]:
x.transpose(0, 2)

tensor([[[1, 3],
         [2, 0]],

        [[2, 0],
         [1, 3]],

        [[1, 3],
         [2, 0]]])

In [43]:
a = torch.full((2, 3), 1)
a

tensor([[1, 1, 1],
        [1, 1, 1]])

In [44]:
b = a.view(-1)

In [45]:
b

tensor([1, 1, 1, 1, 1, 1])

In [46]:
a[1, 1] = 2
a

tensor([[1, 1, 1],
        [1, 2, 1]])

In [47]:
b

tensor([1, 1, 1, 1, 2, 1])

In [48]:
b[0] = 9
a, b

(tensor([[9, 1, 1],
         [1, 2, 1]]), tensor([9, 1, 1, 1, 2, 1]))

In [50]:
import torch, torchvision
cifar = torchvision.datasets.CIFAR10('./cifar10', train = True, download = True)

  0%|          | 0/170498071 [00:00<?, ?it/s]

Extracting ./cifar10/cifar-10-python.tar.gz to ./cifar10


In [51]:
x = torch.from_numpy(cifar.data).permute(0, 3, 1, 2).float() / 255
print(x.dtype, x.size(), x.min().item(), x.max().item())

torch.float32 torch.Size([50000, 3, 32, 32]) 0.0 1.0


In [52]:
x = x[:48]
torchvision.utils.save_image(x, 'cifar-4x12.png', nrow = 12, pad_value = 1.0)

In [53]:
x.transpose_(2, 3)
torchvision.utils.save_image(x, 'cifar-4x12-rotated.png', nrow = 12, pad_value = 1.0)

In [54]:
x[0:, 1:3].fill_(0)
torchvision.utils.save_image(x, 'cifar-4x12-rotated-and-red.png', nrow = 12, pad_value = 1.0)

In [55]:
torchvision.utils.save_image(x, 'cifar-4x12-rotated-and-red_0_padding.png', nrow = 12, pad_value = 0.0)

In [56]:
x = torch.empty(100, 4).normal_(2)
x.mean(0)

tensor([2.2125, 2.1518, 2.1130, 2.0379])

In [57]:
x -= x.mean(0)

In [58]:
x

tensor([[ 8.2423e-01, -1.8794e+00,  1.0914e+00,  6.1428e-01],
        [ 6.9219e-01,  5.1692e-01,  1.0667e-01,  1.5207e+00],
        [-6.7334e-03,  7.5151e-01,  9.3283e-01, -8.2551e-01],
        [ 4.9775e-01, -7.9520e-01, -2.8689e+00, -6.9835e-01],
        [-1.9793e+00,  2.6696e-02,  4.2104e-01,  1.1784e-01],
        [ 3.1654e-02,  1.0948e+00,  1.3004e+00, -1.1246e+00],
        [ 1.5701e+00,  5.7786e-01,  3.9940e-01,  1.3431e+00],
        [-7.6356e-01,  5.1215e-01,  1.4704e+00, -1.8484e+00],
        [-1.2835e+00,  1.3482e-01, -9.8052e-02, -9.8499e-01],
        [-4.6002e-01, -2.3753e-01, -1.9026e+00,  1.1158e+00],
        [ 2.1410e+00, -8.0892e-02,  6.3328e-01, -1.2391e+00],
        [ 2.5054e-01, -5.0260e-01, -1.9900e+00,  7.0891e-01],
        [-1.2512e+00, -6.6695e-01, -4.8909e-01,  1.5770e-01],
        [ 7.4293e-01, -6.4667e-01,  5.9493e-01,  1.1390e-01],
        [ 1.2273e-01, -1.2693e-01, -1.8454e-01, -1.2623e+00],
        [-7.6039e-01,  1.3631e+00, -1.7826e+00, -2.8570e-03],
        

In [59]:
x.mean(0)

tensor([-1.5497e-07,  7.5102e-08,  3.5763e-08, -2.6345e-07])

In [60]:
p = torch.rand(2, 5)
q = torch.rand(5, 4)
torch.einsum('ij,jk->ik', p, q)

tensor([[0.4310, 0.7689, 0.2702, 0.7633],
        [1.2320, 2.5876, 1.0041, 2.6029]])

In [61]:
p@q

tensor([[0.4310, 0.7689, 0.2702, 0.7633],
        [1.2320, 2.5876, 1.0041, 2.6029]])

In [62]:
x = torch.zeros(2, 4)
x.storage()

 0.0
 0.0
 0.0
 0.0
 0.0
 0.0
 0.0
 0.0
[torch.storage._TypedStorage(dtype=torch.float32, device=cpu) of size 8]

In [63]:
x.to("cuda")

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.]], device='cuda:0')

In [64]:
x.device

device(type='cpu')

In [65]:
y = x.to("cuda")
y.device

device(type='cuda', index=0)

In [67]:
q = x.storage()
q[4] = 1.0
x

tensor([[0., 0., 0., 0.],
        [1., 0., 0., 0.]])

In [68]:
p

tensor([[0.1577, 0.2961, 0.1640, 0.0486, 0.3187],
        [0.1270, 0.7989, 0.8838, 0.9594, 0.7400]])

In [69]:
p.view(-1)

tensor([0.1577, 0.2961, 0.1640, 0.0486, 0.3187, 0.1270, 0.7989, 0.8838, 0.9594,
        0.7400])

In [70]:
p = torch.rand(5, 10)

In [71]:
p

tensor([[0.7318, 0.2010, 0.5595, 0.5062, 0.3350, 0.5976, 0.7998, 0.2690, 0.2106,
         0.6734],
        [0.0979, 0.2985, 0.4557, 0.2164, 0.2057, 0.0060, 0.8921, 0.3104, 0.6777,
         0.8344],
        [0.5921, 0.7068, 0.0893, 0.1581, 0.9930, 0.6128, 0.1094, 0.4709, 0.9261,
         0.6377],
        [0.9439, 0.6252, 0.2160, 0.8444, 0.5556, 0.0658, 0.9271, 0.4586, 0.6317,
         0.0135],
        [0.3984, 0.5015, 0.7176, 0.2548, 0.9847, 0.6896, 0.7854, 0.8596, 0.1800,
         0.9743]])

In [72]:
p.view(-1)

tensor([0.7318, 0.2010, 0.5595, 0.5062, 0.3350, 0.5976, 0.7998, 0.2690, 0.2106,
        0.6734, 0.0979, 0.2985, 0.4557, 0.2164, 0.2057, 0.0060, 0.8921, 0.3104,
        0.6777, 0.8344, 0.5921, 0.7068, 0.0893, 0.1581, 0.9930, 0.6128, 0.1094,
        0.4709, 0.9261, 0.6377, 0.9439, 0.6252, 0.2160, 0.8444, 0.5556, 0.0658,
        0.9271, 0.4586, 0.6317, 0.0135, 0.3984, 0.5015, 0.7176, 0.2548, 0.9847,
        0.6896, 0.7854, 0.8596, 0.1800, 0.9743])

In [73]:
p.view(3)

RuntimeError: ignored

In [74]:
p.view(3, -1)

RuntimeError: ignored

In [75]:
p = torch.rand(4, 6)

In [76]:
p

tensor([[0.2530, 0.9665, 0.6470, 0.5497, 0.3296, 0.7133],
        [0.5818, 0.8642, 0.8079, 0.9752, 0.8950, 0.8242],
        [0.5858, 0.3719, 0.6390, 0.0552, 0.8391, 0.8175],
        [0.9610, 0.1042, 0.0969, 0.9014, 0.3992, 0.9062]])

In [77]:
p.view(-1)

tensor([0.2530, 0.9665, 0.6470, 0.5497, 0.3296, 0.7133, 0.5818, 0.8642, 0.8079,
        0.9752, 0.8950, 0.8242, 0.5858, 0.3719, 0.6390, 0.0552, 0.8391, 0.8175,
        0.9610, 0.1042, 0.0969, 0.9014, 0.3992, 0.9062])

In [78]:
p.view(2, -1)

tensor([[0.2530, 0.9665, 0.6470, 0.5497, 0.3296, 0.7133, 0.5818, 0.8642, 0.8079,
         0.9752, 0.8950, 0.8242],
        [0.5858, 0.3719, 0.6390, 0.0552, 0.8391, 0.8175, 0.9610, 0.1042, 0.0969,
         0.9014, 0.3992, 0.9062]])

In [79]:
p.view(4, -1)

tensor([[0.2530, 0.9665, 0.6470, 0.5497, 0.3296, 0.7133],
        [0.5818, 0.8642, 0.8079, 0.9752, 0.8950, 0.8242],
        [0.5858, 0.3719, 0.6390, 0.0552, 0.8391, 0.8175],
        [0.9610, 0.1042, 0.0969, 0.9014, 0.3992, 0.9062]])

In [80]:
p.view(3, -1)

tensor([[0.2530, 0.9665, 0.6470, 0.5497, 0.3296, 0.7133, 0.5818, 0.8642],
        [0.8079, 0.9752, 0.8950, 0.8242, 0.5858, 0.3719, 0.6390, 0.0552],
        [0.8391, 0.8175, 0.9610, 0.1042, 0.0969, 0.9014, 0.3992, 0.9062]])

In [81]:
p.view(6, -1)

tensor([[0.2530, 0.9665, 0.6470, 0.5497],
        [0.3296, 0.7133, 0.5818, 0.8642],
        [0.8079, 0.9752, 0.8950, 0.8242],
        [0.5858, 0.3719, 0.6390, 0.0552],
        [0.8391, 0.8175, 0.9610, 0.1042],
        [0.0969, 0.9014, 0.3992, 0.9062]])

In [82]:
p.view(2, 3, -1)

tensor([[[0.2530, 0.9665, 0.6470, 0.5497],
         [0.3296, 0.7133, 0.5818, 0.8642],
         [0.8079, 0.9752, 0.8950, 0.8242]],

        [[0.5858, 0.3719, 0.6390, 0.0552],
         [0.8391, 0.8175, 0.9610, 0.1042],
         [0.0969, 0.9014, 0.3992, 0.9062]]])

In [1]:
import torch

# New Section