In [ ]:
import torch
import torch.nn.functional as F

nb_symbols = 6
s = torch.tensor([0, 1, 2, 3, 2, 1, 0, 5, 0, 5, 0])
x = F.one_hot(s, num_classes = nb_symbols)
x

tensor([[1, 0, 0, 0, 0, 0],
        [0, 1, 0, 0, 0, 0],
        [0, 0, 1, 0, 0, 0],
        [0, 0, 0, 1, 0, 0],
        [0, 0, 1, 0, 0, 0],
        [0, 1, 0, 0, 0, 0],
        [1, 0, 0, 0, 0, 0],
        [0, 0, 0, 0, 0, 1],
        [1, 0, 0, 0, 0, 0],
        [0, 0, 0, 0, 0, 1],
        [1, 0, 0, 0, 0, 0]])

In [ ]:
from torch.nn.utils.rnn import pack_padded_sequence
pack_padded_sequence(torch.tensor([[[1.], [2.]],
                                   [[3.], [4.]],
                                   [[5.], [0.]]]),
                     torch.tensor([3, 2]))


PackedSequence(data=tensor([[1.],
        [2.],
        [3.],
        [4.],
        [5.]]), batch_sizes=tensor([2, 2, 1]), sorted_indices=None, unsorted_indices=None)

In [4]:
import torch
import torch.nn as nn

e = nn.Embedding(num_embeddings = 10, embedding_dim=3)
x = torch.tensor([[1, 1, 2, 2], [0, 1, 9, 9]])

y = e(x)
y

tensor([[[ 0.0731,  1.2307, -0.8088],
         [ 0.0731,  1.2307, -0.8088],
         [-0.0144, -0.0587, -0.1512],
         [-0.0144, -0.0587, -0.1512]],

        [[ 0.5209,  0.7174,  0.0241],
         [ 0.0731,  1.2307, -0.8088],
         [ 0.7712, -0.1428, -0.8360],
         [ 0.7712, -0.1428, -0.8360]]], grad_fn=<EmbeddingBackward0>)

In [5]:
e.weight[1]

tensor([ 0.0731,  1.2307, -0.8088], grad_fn=<SelectBackward0>)