In [6]:
import torch
import torch.nn as nn
import torch.nn.functional as F

x = torch.tensor([[[0., 0., 1., 0., 0., 0.]]])
k = torch.tensor([[[1., 2., 3.]]])
F.conv1d(x, k)

tensor([[[3., 2., 1., 0.]]])

In [7]:
F.conv_transpose1d(x, k)

tensor([[[0., 0., 1., 2., 3., 0., 0., 0.]]])

In [10]:
x = torch.tensor([[[1., 0., 0., 0., -1.]]])
m = nn.ConvTranspose1d(1, 1, kernel_size=3)

with torch.autograd.no_grad():
    m.bias.zero_()
    m.weight.copy_(torch.tensor([1, 2, 1]))

y = m(x)
y

tensor([[[ 1.,  2.,  1.,  0., -1., -2., -1.]]], grad_fn=<ConvolutionBackward0>)